-- ==========================================
-- Supabase 完整資料庫 Schema 設定檔
-- 可以在 Supabase 的 SQL Editor 貼上並執行
-- ==========================================

-- 1. 建立完整填寫資料表 (包含序位資訊)
CREATE TABLE IF NOT EXISTS public.survey_responses_full (
    id bigint generated by default as identity primary key,
    timestamp timestamptz not null default now(),
    region text not null,
    "examYear" text not null,
    identity text,
    "chineseScore" text,
    "mathScore" text,
    "englishScore" text,
    "socialScore" text,
    "scienceScore" text,
    "essayScore" text,
    email text,
    "inviteCode" text,
    "minRatio" numeric,
    "maxRatio" numeric,
    "minRankInterval" integer,
    "maxRankInterval" integer,
    custom_answers jsonb default '{}'::jsonb
);

-- 2. 建立無序位填寫資料表
CREATE TABLE IF NOT EXISTS public.survey_responses_skip_ranking (
    id bigint generated by default as identity primary key,
    timestamp timestamptz not null default now(),
    region text not null,
    "examYear" text not null,
    identity text,
    "chineseScore" text,
    "mathScore" text,
    "englishScore" text,
    "socialScore" text,
    "scienceScore" text,
    "essayScore" text,
    email text,
    "inviteCode" text,
    custom_answers jsonb default '{}'::jsonb
);

-- 3. 建立系統設定資料表
CREATE TABLE IF NOT EXISTS public.survey_config (
    id bigint generated by default as identity primary key,
    announcement_date timestamptz,
    custom_questions jsonb default '[]'::jsonb,
    subject_score_start_time timestamptz,
    subject_score_end_time timestamptz,
    subject_score_enabled boolean default true,
    system_start_time timestamptz,
    system_end_time timestamptz,
    system_enabled boolean default true
);

-- 預設插入一筆系統設定 (若為空)
INSERT INTO public.survey_config (id, announcement_date, custom_questions, subject_score_enabled, system_enabled)
VALUES (1, '2026-06-16T12:00:00+08:00', '[]'::jsonb, true, true)
ON CONFLICT (id) DO NOTHING;

-- ==========================================
-- 安全性規則 (Row Level Security - RLS)
-- ==========================================

-- 啟用 RLS
ALTER TABLE public.survey_responses_full ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.survey_responses_skip_ranking ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.survey_config ENABLE ROW LEVEL SECURITY;

-- 允許任何人都可以新增資料 (提供前台填寫)
CREATE POLICY "Allow public insert to survey_responses_full" 
ON public.survey_responses_full FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public insert to survey_responses_skip_ranking" 
ON public.survey_responses_skip_ranking FOR INSERT WITH CHECK (true);

-- 允許任何人都可以讀取出系統設定檔 (以提供前端介面邏輯)
CREATE POLICY "Allow public select on survey_config" 
ON public.survey_config FOR SELECT USING (true);

-- ==========================================
-- (選用) 設定管理員專用的讀寫存取權限
-- 如果你希望前台圖表可以公開顯示，也可調整為 USING (true) 讓所有人都可以 Select
-- ==========================================
CREATE POLICY "Allow public select on survey_responses_full" 
ON public.survey_responses_full FOR SELECT USING (true);

CREATE POLICY "Allow public select on survey_responses_skip_ranking" 
ON public.survey_responses_skip_ranking FOR SELECT USING (true);

-- 針對設定檔的更新操作，若你已經有對應的 Auth，可限制 authenticated
CREATE POLICY "Allow authenticated update on survey_config" 
ON public.survey_config FOR UPDATE USING (true);
CREATE POLICY "Allow authenticated insert on survey_config" 
ON public.survey_config FOR INSERT WITH CHECK (true);

-- ==========================================
-- 管理員認證與系統日誌
-- ==========================================

-- 4. 管理員帳號
CREATE TABLE IF NOT EXISTS public.admin_users (
    id bigint generated by default as identity primary key,
    password text not null
);
INSERT INTO public.admin_users (id, password) VALUES (1, 'admin123') ON CONFLICT (id) DO NOTHING;

-- 5. 管理員登入紀錄
CREATE TABLE IF NOT EXISTS public.admin_logs (
    id bigint generated by default as identity primary key,
    login_time timestamptz not null default now(),
    status text not null,
    ip_address text,
    user_agent text
);

ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert on admin_logs" ON public.admin_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select on admin_logs" ON public.admin_logs FOR SELECT USING (true); 

-- 建立檢查密碼的 RPC
CREATE OR REPLACE FUNCTION verify_admin_password(p_password text, p_user_agent text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  is_valid boolean;
  client_ip text;
BEGIN
  SELECT EXISTS(SELECT 1 FROM public.admin_users WHERE password = p_password) INTO is_valid;
  
  BEGIN
    client_ip := current_setting('request.headers', true)::json->>'x-forwarded-for';
  EXCEPTION WHEN OTHERS THEN
    client_ip := 'unknown';
  END;

  INSERT INTO public.admin_logs (status, ip_address, user_agent) 
  VALUES (CASE WHEN is_valid THEN 'SUCCESS' ELSE 'FAILED' END, client_ip, p_user_agent);
  
  RETURN is_valid;
END;
$$;

-- 提供修改密碼的 RPC
CREATE OR REPLACE FUNCTION update_admin_password(old_password text, new_password text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  is_valid boolean;
BEGIN
  SELECT EXISTS(SELECT 1 FROM public.admin_users WHERE password = old_password) INTO is_valid;
  IF is_valid THEN
    UPDATE public.admin_users SET password = new_password WHERE password = old_password;
    RETURN true;
  END IF;
  RETURN false;
END;
$$;

